<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Exemple POO avec PHP</title>
</head>

<body>
    <div class="container py-3">
        <div class="jumbotron">
            <h3>Liste de clients</h3>
        </div>
        <?php if (isset($_GET['notif'])) : ?>
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php
                if ($_GET['notif'] == 'add') echo 'Client ajouté avec succés';
                if ($_GET['notif'] == 'update') echo 'Client modifié avec succés';
                if ($_GET['notif'] == 'delete') echo 'Client supprimé avec succés';
                ?>
            </div>
        <?php endif ?>
        <a href="create.php" class="btn btn-primary">New Client</a><br><br>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Téléphone</th>
                    <th>Opérations</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($clientsList as $key => $client) : ?>
                    <tr>
                        <th><?= $key ?></th>
                        <td><?= $client['nom'] ?></td>
                        <td><?= $client['prenom'] ?></td>
                        <td><?= $client['tel'] ?></td>
                        <td>
                            <a href="#" class="btn btn-outline-info">Details</a>
                            <a href="edit.php?id=<?= $client['id'] ?>" class="btn btn-outline-success">Modifier</a>
                            <a href="delete.php?id=<?= $client['id'] ?>" class="btn btn-outline-danger">Supprimer</a>
                        </td>
                    </tr>
                <?php endforeach; ?>

            </tbody>
        </table>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>

</html>